- hosts: all
  tasks:
  - name: Install Apache
    package:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - "{{ package_name }}"
      - unzip

  - name: Start and Enable Apache
    systemd:
      name: "{{ service_name }}"
      state: started
      enabled: yes  

  - name: Download a Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page294/shapel.zip
      dest: /tmp/shapel.zip

  - name: Extract Template
    unarchive:
      src: /tmp/shapel.zip
      dest: /tmp/
      remote_src: yes

  - name: Move Template to /var/www/html
    shell: mv /tmp/shapel-html/* /var/www/html/  
    args:
      creates: /var/www/html/gallery.html

