- hosts: all
  tasks:
  - name: Disable SELinux on RedHat
    selinux:
      state: disabled
    when: ansible_os_family == "RedHat"

  - name: Install packages on RedHat
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - httpd
      - unzip
    when: ansible_os_family == "RedHat"

  - name: Install packages on Debian
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apache2
      - unzip
    when: ansible_os_family == "Debian"

  - name: Start and Enable Apache on RedHat
    systemd:
      name: httpd
      state: started
      enabled: yes  
    when: ansible_os_family == "RedHat"

  - name: Start and Enable Apache on Ubuntu
    systemd:
      name: apache2
      state: started
      enabled: yes 
    when: ansible_os_family == "Debian"

  - name: Download a Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page294/shapel.zip
      dest: /tmp/shapel.zip

  - name: Extract Template
    unarchive:
      src: /tmp/shapel.zip
      dest: /tmp/
      remote_src: yes

  - name: Move Template to /var/www/html
    shell: mv /tmp/shapel-html/* /var/www/html/  
    args:
      creates: /var/www/html/gallery.html
